version: '2'
networks:
  ram:
    external:
      name: ram
services:
  ram-postgis:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ram
      POSTGRES_USER: ram
      POSTGRES_DB: ram
    volumes:
      - ./setup/create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
      - ./setup/setup-extensions.sh:/docker-entrypoint-initdb.d/setup-extensions.sh
    networks:
      - ram
  ram-minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorageengine
    command: server /export
    networks:
      - ram