version: '2'
services:
  rra-postgis:
    image: mdillon/postgis
    network_mode: host
    environment:
      POSTGRES_PASSWORD: rra
      POSTGRES_USER: rra
      POSTGRES_DB: rra
  rra-minio:
    image: minio/minio
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorageengine
    command: server /export
  rra-api:
    build: ./
    container_name: rra-api
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: yarn start
    environment:
      DB_CONNECTION: postgresql://rra:rra@localhost:5432/rra
      STORAGE_HOST: localhost
      ANL_CONTAINER: wbtransport/rra-analysis:latest-stable
      ANL_DB: postgresql://rra:rra@localhost:5432/rra
      ANL_STORAGE_HOST: localhost
  rra-frontend:
    image: wbtransport/rra-frontend:latest-dev
    network_mode: host
