version: '2'
services:
  ram-postgis:
    image: mdillon/postgis:9.6
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: ram
      POSTGRES_USER: ram
      POSTGRES_DB: ram
    volumes:
      - ./setup/create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
      - ./setup/setup-extensions.sh:/docker-entrypoint-initdb.d/setup-extensions.sh
  ram-minio:
    image: minio/minio
    ports:
      - 9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniostorageengine
    # volumes:
    #   - /guts/projects/ram/minio-stuff/export:/export
    #   - /guts/projects/ram/minio-stuff/config:/root/.minio
    command: server /export
  ram-api:
    build: ./
    ports:
      - 4000
    environment:
      DS_ENV: test
      DB_CONNECTION: postgresql://ramtest:ramtest@ram-postgis:5432/ramtest
      STORAGE_HOST: ram-minio
    links:
      - ram-postgis
      - ram-minio